services:
  web:
    build: .
    ports:
      - "127.0.0.1:${PORT}:80"
    volumes:
      - .:/var/www/html
    environment:
      - TZ=Europe/Prague
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - TOGGL_CLIENT_NAME=ProfiSMS
      #- TOGGL_CLIENT_NAME=Galileo
      - TOGGL_API_TOKEN=${TOGGL_API_TOKEN}
      - "CHART_TITLE=Jak moc pracuje Krato pro ProfiSMS?"
      #- "CHART_TITLE=Jak moc pracuje Krato pro Galileo?"
    restart: always

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
